### ISSUE TITLE
Development workflow proposal

### ISSUE THREAD

**Issue by Eloston** [huskyroboticsteam/2016-17#1]
I think it would be nice to use the pull request feature of GitHub. Here's what I'm thinking:
- There can be those that manage the different software components who are collaborators on this repository.
- Those who are developing on some component can fork this repository, push their changes, and then make a pull request on this repository. GitHub has a nice UI to guide users through this. GitHub also has some nice documentation that can step users through the git commands they will need to use.
- Collaborators will then review the pull request, requesting any changes as necessary, and then merge it.

This workflow will allow for some quality control, and it makes it easier for users to experiment without accidentally screwing with this repository.

**Comment by Obbay2** [comment]
This would be nice since last year's repository turned into a huge mess!

**Comment by BigOto2** [comment]
Sounds like a good idea, when we delegate tasks this Saturday I will try this out.
